project:
  type: website
  


website:
  title: "Heart Disease Prediction Analysis"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Data Description"
        href: data.qmd
      - text: "Research Analysis"
        href: research.qmd
      - text: "Conclusion"
        href: conclusion.qmd
      - text: "References"
        href: references.qmd
        
      
format: 
  html: 
   code-fold: true

      
